In [119]:
from scipy.stats import gamma
import numpy as np
import math

nU = 1000
nI = 1000
k = 30
mean_y = 3
shape_para = 1
a = shape_para
a_prime = shape_para
b_prime = a / math.sqrt(mean_y / k)
c = shape_para
c_prime = shape_para
d_prime = c / math.sqrt(mean_y / k)

rng = np.random.default_rng()

In [120]:
eta = gamma.ppf(rng.uniform(0.15, 0.85, nI), a=c_prime, scale=d_prime / c_prime).reshape(nI, 1)

In [121]:
Beta = np.empty(shape = (nI, k))
for i in range(nU):
    Beta[i, :] = gamma.ppf(rng.uniform(0.15, 0.85, k), a=c, scale=1 / eta[i])

In [122]:
Beta

array([[0.84597781, 0.46057439, 2.6805792 , ..., 2.43260963, 0.4236302 ,
        2.15175231],
       [0.10381689, 0.06393169, 0.21348347, ..., 0.41207671, 0.58880833,
        0.25469564],
       [0.3833636 , 0.195321  , 0.24254739, ..., 0.82611442, 0.12391074,
        0.27105774],
       ...,
       [0.23822667, 0.67344069, 1.13441099, ..., 0.25234503, 0.19175981,
        1.07892712],
       [2.70359599, 0.67607078, 1.99934018, ..., 2.60213503, 0.38459295,
        2.46986286],
       [0.41570627, 0.25429254, 0.0934597 , ..., 0.14167892, 0.04669157,
        0.06074167]])

In [123]:
Beta2 = np.empty(shape = (nI, k))
for i in range(nU):
    Beta2[i, :] = gamma.ppf(rng.uniform(0.15, 0.85, k), a=c, scale=1 / eta[i])

In [124]:
Beta2

array([[1.18696212, 2.07457112, 1.14130716, ..., 0.34955108, 0.96732484,
        0.64344236],
       [0.31720796, 0.39776725, 0.12868773, ..., 0.32044845, 0.55237434,
        0.32042534],
       [0.23781923, 0.35909612, 0.49681936, ..., 1.32087655, 0.12033007,
        0.33813073],
       ...,
       [0.44847261, 0.18234976, 1.07872412, ..., 0.67560984, 0.14410704,
        0.12591793],
       [0.58881026, 0.37181046, 0.63155107, ..., 1.66953807, 0.70761957,
        1.40085748],
       [0.11655522, 0.39304997, 0.21894097, ..., 0.46831536, 0.08225518,
        0.18063678]])

In [130]:
max_para_change = 1e-1
abs(Beta - Beta2) > max_para_change

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True, False, ..., False, False, False],
       [ True,  True,  True, ...,  True, False, False],
       ...,
       [ True,  True, False, ...,  True, False,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True, False,  True]])

In [131]:
Beta[Beta > Beta2]

array([2.6805792 , 2.87169222, 1.64599303, ..., 0.29486936, 0.30583624,
       0.34247146])

TypeError: 'numpy.ndarray' object is not callable